schema_version: 0.1.0
initialPageId: survey

pages:
  - id: survey
    components:
      - type: survey
        props:
          items:
            - id: mood
              text: "How are you feeling today?"
              answer: likert5
      - type: buttons
        props:
          buttons:
            - id: done
              text: "Submit"
              action:
                type: go_to
                target: thanks

  - id: thanks
    end: true
    endRedirectUrl: "https://app.prolific.com/submissions/complete?cc=HELLO123"
    components:
      - type: text
        props:
          text: "Thanks for your response!"
