schema_version: 0.1.0
initialPageId: intro

pages:
  - id: intro
    components:
      - type: text
        props:
          text: "Welcome to the simple survey."
      - type: buttons
        props:
          buttons:
            - id: intro-next
              text: "Next"
              action:
                type: go_to
                target: question

  - id: question
    components:
      - type: text
        props:
          text: "How are you feeling today?"
      - type: buttons
        props:
          buttons:
            - id: question-submit
              text: "Finish"
              action:
                type: go_to
                target: outro

  - id: outro
    end: true
    components:
      - type: text
        props:
          text: "Thanks for participating!"

