site_name: "Pairit Docs"
site_url: https://pairit-lab-docs.web.app/
nav:
  - Experimenter:
      - Overview: index.md
      - Quickstart: quickstart.md
      - Concepts: concepts.md
      - Configuration: configuration.md
      - Components: components.md
      - CLI: cli.md
      - Examples: examples.md
  - Components:
      - Text: components/text.md
      - Button: components/buttons.md
      - Survey: components/survey.md
      - Matchmaking: components/matchmaking.md
      - Chat: components/chat.md
      - Agents: components/agents.md
      - Workspace: components/workspace.md
      - Media: components/media.md
      - Form: components/form.md
      - Custom Components: components/custom.md
  - Developer:
      - Architecture: dev/architecture.md
      - Deployment: dev/deployment.md
      - Runtime: dev/runtime.md
      - Backend: dev/backend.md
      - Authentication: dev/authentication.md
      - Realtime: dev/realtime.md
      - Storage: dev/storage.md
      - Validation: dev/validation.md
      - Survey: dev/survey.md
      - Component Registry: dev/registry.md
      - Matchmaking: dev/matchmaking.md
theme:
  name: shadcn
  show_title: true
  show_stargazers: false
  pygments_style:
    light: shadcn-light
    dark: github-dark
  icon: heroicons:rocket-launch
  topbar_sections: false
markdown_extensions:
  - codehilite